version: '3.3'
services:
    browser-ide:
        restart: always
        container_name: browser-ide
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'browser-ide:/root'
            - "./browser-ide/Caddyfile:/etc/Caddyfile"
            - "./browser-ide/supervisor.conf:/etc/supervisor.conf"
        image: 'tthebc01/browser-ide:latest'
        expose:
            - "8080"
            - "8888"
        networks: 
            - proxy-network
        environment:
            - AUTHP_ADMIN_USER=${AUTHP_ADMIN_USER}
            - AUTHP_ADMIN_SECRET=${AUTHP_ADMIN_SECRET}
            - AUTHP_ADMIN_EMAIL=${AUTHP_ADMIN_EMAIL}
            - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
            - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
            - JWT_SHARED_KEY=${JWT_SHARED_KEY}
            
    ipfs-node:
        restart: always
        container_name: ipfs_node
        volumes:
            - 'ipfs-staging:/export'
            - 'ipfs-data:/data/ipfs'
        expose:
            - '4001'
            - '4001/udp'
            - '5001'
        image: 'ipfs/go-ipfs:latest'
        networks: 
            - proxy-network
            
    glances-export:
        restart: always
        container_name: glances-export
        image: 'nicolargo/glances:latest-full'
        expose:
            - "9091"
        environment:
            GLANCES_OPT: "--export prometheus --quiet"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./glances/glances.conf:/glances/conf/glances.conf"
        pid: "host"
        networks: 
            - proxy-network
            
    glances:
        restart: always
        container_name: glances
        image: 'nicolargo/glances:latest-full'
        expose:
            - "61208"
        environment:
            GLANCES_OPT: "-w"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        pid: "host"
        networks: 
            - proxy-network
            
    prometheus:
        restart: always
        image: prom/prometheus:latest
        container_name: prometheus
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
            - 'prometheus-data:/prometheus'
        expose:
            - "9090"
        depends_on:
            - cadvisor
            - browser-ide
            - glances
        networks: 
            - proxy-network
            
    cadvisor:
        restart: always
        image: gcr.io/cadvisor/cadvisor:latest
        container_name: cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        expose:
            - "8080"
        depends_on:
            - browser-ide
            - tunnel
            - ipfs-node
        networks: 
            - proxy-network
        command: 
            - '-url_base_prefix=/cadvisor'
            
    grafana:
        restart: always
        image: grafana/grafana-enterprise
        container_name: grafana
        volumes:
            - grafana-storage:/var/lib/grafana
            - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
            - "./grafana/cloud-in-a-box-grafana.yaml:/etc/grafana/provisioning/dashboards/cloud-in-a-box-grafana.yaml"
            - "./grafana/dashboards:/etc/grafana/dashboards"
            - "./grafana/prom-data-source.yaml:/etc/grafana/provisioning/datasources/prom-data-source.yaml"
        expose:
            - "3000"
        depends_on:
            - prometheus
        networks: 
            - proxy-network
        
    tunnel:
        restart: always
        container_name: argo-tunnel
        image: 'cloudflare/cloudflared:2022.5.1'
        command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
        networks: 
            - proxy-network
        depends_on:
            - browser-ide

volumes:
  browser-ide:
  ipfs-staging:
  ipfs-data:
  prometheus-data:
  grafana-storage:
  
networks:
  proxy-network:
    name: proxy-network