# prometheus.yaml
global:
  scrape_interval: 5s # default is 1 minute

scrape_configs:
  - job_name: caddy
    static_configs:
      - targets: ['browser-ide:2222']
  - job_name: cadvisor
    metrics_path: /cadvisor/metrics
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'glances_exporter'
    static_configs:
      - targets: ['glances-export:9091']