{
 "title": "Caddy Server",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(caddy_http_response_size_bytes_bucket{instance=\"browser-ide:2222\", code=\"200\", handler=\"reverse_proxy\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reverse Proxy Requests Rate",
   "type": "timeseries",
   "description": "Avg HTTP requests per minute on all reverse proxy routes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{instance=\"browser-ide:2222\", handler=\"reverse_proxy\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(caddy_http_request_duration_seconds_sum{instance=\"browser-ide:2222\", code=\"200\", handler=\"reverse_proxy\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "caddy_http_request_errors_total{instance=\"browser-ide:2222\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}