{
 "title": "Host Performance",
 "time": { "from": "2022-06-20T19:57:25.109Z", "to": "2022-06-20T20:24:07.392Z" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "glances_mem_percent{instance=\"glances-export:9091\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "glances_cpu_system{instance=\"glances-export:9091\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "glances_docker_glances_network_rx{instance=\"glances-export:9091\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "glances_docker_glances_network_tx{instance=\"glances-export:9091\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "glances_fs__etc_hostname_percent{instance=\"glances-export:9091\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}